import { Store, Product, User, Order, Delivery } from "../types/marketplace";

export const MOCK_USERS: Record<string, User> = {
  client: {
    id: "usr_client_01",
    nom: "Ndong Mba",
    prenom: "Marc",
    email: "marc.ndong@gmail.com",
    telephone: "+241 077 45 89 12",
    role: "client",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    location: {
      province: "Estuaire",
      ville: "Libreville",
      quartier: "Nzeng-Ayong",
      repere_texte: "Face pharmacie de Nzeng-Ayong, grand portail vert à 50m du carrefour GP",
      telephone: "+241 077 45 89 12",
    },
    isVerified: true,
    createdAt: "2024-01-15",
  },
  vendeur: {
    id: "usr_vendeur_01",
    nom: "Mengue",
    prenom: "Tatiana",
    email: "contact@saveursdugabon.ga",
    telephone: "+241 074 12 34 56",
    role: "vendeur",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    storeId: "store_02",
    location: {
      province: "Estuaire",
      ville: "Akanda",
      quartier: "Angondjé Château",
      repere_texte: "À côté de la station Total Angondjé, bâtiment R+1 vitré",
      telephone: "+241 074 12 34 56",
    },
    isVerified: true,
    createdAt: "2023-11-20",
  },
  livreur: {
    id: "usr_livreur_01",
    nom: "Obame",
    prenom: "Yannick",
    email: "yannick.express@nexora.ga",
    telephone: "+241 066 98 74 12",
    role: "livreur",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    vehicleType: "moto",
    location: {
      province: "Estuaire",
      ville: "Libreville",
      quartier: "Louis",
      repere_texte: "Zone d'attente Express Carrefour Louis",
      telephone: "+241 066 98 74 12",
    },
    isVerified: true,
    createdAt: "2024-02-01",
  },
  admin: {
    id: "usr_admin_01",
    nom: "Bongo-Nzue",
    prenom: "Alain (Direction)",
    email: "admin@nexora.ga",
    telephone: "+241 077 00 00 01",
    role: "admin",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    isVerified: true,
    createdAt: "2023-01-01",
  },
};

export const MOCK_STORES: Store[] = [
  {
    id: "store_01",
    nom: "L'Atelier Pierre de Mbigou & Arts",
    slug: "atelier-mbigou-arts",
    description: "Authentiques sculptures traditionnelles gabonaises, objets d'art en pierre de Mbigou et masques Punu sculptés main.",
    logo: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80",
    ownerId: "usr_vendeur_02",
    ownerName: "Maître Sculpteur Moussavou",
    rating: 4.9,
    reviewsCount: 84,
    verified: true,
    badge: "Artisan Local",
    location: {
      province: "Estuaire",
      ville: "Libreville",
      quartier: "Louis",
      repere_texte: "En face de l'Hôtel Le Cristal, Rue des Artisans",
      telephone: "+241 077 22 33 44",
    },
    phoneAirtelMoney: "077 22 33 44",
    phoneMoovMoney: "066 11 22 33",
    categories: ["maison_artisanat"],
    totalSales: 312,
    isFeatured: true,
    openingHours: "08h30 - 18h30 (Lun-Sam)",
  },
  {
    id: "store_02",
    nom: "Saveurs & Terroir du Gabon",
    slug: "saveurs-terroir-gabon",
    description: "Épicerie fine locale : Chocolat artisanal fèves de Kango, Odika moulu de Makokou, miel pur de la Ngounié et piments d'Oyem.",
    logo: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80",
    ownerId: "usr_vendeur_01",
    ownerName: "Tatiana Mengue",
    rating: 4.8,
    reviewsCount: 142,
    verified: true,
    badge: "Gabon Pro",
    location: {
      province: "Estuaire",
      ville: "Akanda",
      quartier: "Angondjé Château",
      repere_texte: "Carrefour Gigi, bâtiment moderne à droite",
      telephone: "+241 074 12 34 56",
    },
    phoneAirtelMoney: "074 12 34 56",
    phoneMoovMoney: "062 88 99 00",
    categories: ["alimentation_terroir"],
    totalSales: 1250,
    isFeatured: true,
    openingHours: "08h00 - 20h00 (7j/7)",
  },
  {
    id: "store_03",
    nom: "Tech Libreville Hub",
    slug: "tech-libreville-hub",
    description: "Smartphones neufs sous garantie officielle, laptops ultraportables, écouteurs sans fil et accessoires certifiés avec livraison express.",
    logo: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80",
    ownerId: "usr_vendeur_03",
    ownerName: "Patrick Nzé",
    rating: 4.7,
    reviewsCount: 210,
    verified: true,
    badge: "Boutique Officielle",
    location: {
      province: "Estuaire",
      ville: "Libreville",
      quartier: "Oloumi",
      repere_texte: "Zone Industrielle Oloumi, en face de Tractafric",
      telephone: "+241 077 55 66 77",
    },
    phoneAirtelMoney: "077 55 66 77",
    phoneMoovMoney: "066 44 55 66",
    categories: ["high_tech"],
    totalSales: 890,
    isFeatured: true,
    openingHours: "08h00 - 19h00 (Lun-Sam)",
  },
  {
    id: "store_04",
    nom: "Élégance Afro & Wax Couture",
    slug: "elegance-afro-wax",
    description: "Robes modernes en Wax hollandais, chemises homme lin & broderies gabonaises, accessoires faits main par des couturiers de Libreville.",
    logo: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&auto=format&fit=crop&q=80",
    ownerId: "usr_vendeur_04",
    ownerName: "Carine Mougoula",
    rating: 4.9,
    reviewsCount: 96,
    verified: true,
    badge: "Top Vendeur",
    location: {
      province: "Estuaire",
      ville: "Libreville",
      quartier: "Batterie IV",
      repere_texte: "À 100m de l'Ambassade de France, portail blanc",
      telephone: "+241 074 99 88 77",
    },
    phoneAirtelMoney: "074 99 88 77",
    phoneMoovMoney: "062 11 22 44",
    categories: ["mode_beaute"],
    totalSales: 540,
    isFeatured: true,
    openingHours: "09h00 - 18h30 (Mar-Sam)",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_01",
    storeId: "store_02",
    storeName: "Saveurs & Terroir du Gabon",
    nom: "Coffret Chocolat Artisanal Pur Kango (70% Cacao Gabonais)",
    slug: "chocolat-artisanal-kango-70",
    description: "Tablettes d'exception créées à partir des fèves de cacao sélectionnées dans les plantations de Kango. Saveurs intenses, notes fruitées et torréfaction artisanale.",
    prix: 12500,
    prixPromo: 9900,
    categorie: "alimentation_terroir",
    images: [
      "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=600&auto=format&fit=crop&q=80",
    ],
    stock: 28,
    rating: 4.9,
    reviewsCount: 42,
    isFeatured: true,
    isAvailableForExpressDelivery: true,
    badges: ["Terroir Gabonais", "Promo", "Coup de Cœur"],
    specifications: {
      Origine: "Kango, Estuaire (Gabon)",
      Poids: "3 x 100g",
      Conservation: "12 mois à température ambiante",
    },
    createdAt: "2024-02-10",
  },
  {
    id: "prod_02",
    storeId: "store_01",
    storeName: "L'Atelier Pierre de Mbigou & Arts",
    nom: "Sculpture Façonnée Main en Pierre de Mbigou (Motif Protecteur)",
    slug: "sculpture-pierre-mbigou-protecteur",
    description: "Véritable pièce unique en pierre tendre de Mbigou (Province de la Ngounié). Finition polie naturelle, socle en bois de Padouk.",
    prix: 45000,
    prixPromo: 39000,
    categorie: "maison_artisanat",
    images: [
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1569063386798-345908ef9a62?w=600&auto=format&fit=crop&q=80",
    ],
    stock: 4,
    rating: 5.0,
    reviewsCount: 19,
    isFeatured: true,
    isAvailableForExpressDelivery: true,
    badges: ["Artisanat Gabonais", "Pièce Unique"],
    specifications: {
      Origine: "Mbigou, Ngounié (Gabon)",
      Matière: "Pierre de Mbigou & Bois de Padouk",
      Dimensions: "28 cm x 14 cm",
      Poids: "2.4 kg",
    },
    createdAt: "2024-01-20",
  },
  {
    id: "prod_03",
    storeId: "store_03",
    storeName: "Tech Libreville Hub",
    nom: "Smartphone Galaxy S24 Ultra 256Go (Garantie 12 Mois)",
    slug: "samsung-galaxy-s24-ultra",
    description: "Écran Dynamic AMOLED 120Hz, processeur Snapdragon haute performance, quadruple capteur photo 200MP, stylet S-Pen inclus. Compatible réseaux 4G/5G Airtel & Moov Gabon.",
    prix: 780000,
    prixPromo: 725000,
    categorie: "high_tech",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80",
    ],
    stock: 12,
    rating: 4.8,
    reviewsCount: 63,
    isFeatured: true,
    isAvailableForExpressDelivery: true,
    badges: ["Garantie 1 An", "Livraison Express Libreville"],
    specifications: {
      Stockage: "256 Go",
      RAM: "12 Go",
      Garantie: "1 an constructeur",
      Opérateurs: "Tous réseaux (Airtel / Moov Gabon)",
    },
    createdAt: "2024-02-15",
  },
  {
    id: "prod_04",
    storeId: "store_04",
    storeName: "Élégance Afro & Wax Couture",
    nom: "Ensemble Veste & Pantalon Chic Wax & Lin Moderne",
    slug: "ensemble-wax-lin-moderne",
    description: "Création moderne alliant les motifs graphiques du Wax de première qualité à un lin respirant adapté au climat équatorial.",
    prix: 35000,
    categorie: "mode_beaute",
    images: [
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80",
    ],
    stock: 15,
    rating: 4.9,
    reviewsCount: 31,
    isFeatured: true,
    isAvailableForExpressDelivery: false,
    badges: ["Fait Main à Libreville", "Tendance 2024"],
    specifications: {
      Tailles: "S, M, L, XL, XXL disponibles",
      Matière: "Wax 100% Coton & Lin naturel",
      Entretien: "Lavage délicat 30°C",
    },
    createdAt: "2024-01-28",
  },
  {
    id: "prod_05",
    storeId: "store_02",
    storeName: "Saveurs & Terroir du Gabon",
    nom: "Pot d'Odika Pur Torréfié de Makokou (Chocolat Indigène 500g)",
    slug: "odika-pur-makokou-500g",
    description: "Véritable Odika (amandes de mangue sauvage) récolté en forêt primaire d'Ogooué-Ivindo. Indispensable pour vos sauces traditionnelles gabonaises.",
    prix: 8500,
    categorie: "alimentation_terroir",
    images: [
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80",
    ],
    stock: 45,
    rating: 4.8,
    reviewsCount: 57,
    isFeatured: false,
    isAvailableForExpressDelivery: true,
    badges: ["100% Forêt Gabonaise", "Bio"],
    specifications: {
      Poids: "500 g",
      Origine: "Makokou, Ogooué-Ivindo",
    },
    createdAt: "2024-02-05",
  },
  {
    id: "prod_06",
    storeId: "store_03",
    storeName: "Tech Libreville Hub",
    nom: "Écouteurs Sans Fil Réduction de Bruit Active (ANC)",
    slug: "ecouteurs-sans-fil-anc",
    description: "Autonomie 32 heures avec boîtier, réduction active du bruit ambiant, appels clairs même en circulation urbaine, résistant à la sueur.",
    prix: 28000,
    prixPromo: 22500,
    categorie: "high_tech",
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80",
    ],
    stock: 20,
    rating: 4.7,
    reviewsCount: 38,
    isFeatured: false,
    isAvailableForExpressDelivery: true,
    badges: ["Promo Flash", "Top Vente"],
    specifications: {
      Autonomie: "8h + 24h boîtier",
      Connectivité: "Bluetooth 5.3",
      Garantie: "6 mois échange standard",
    },
    createdAt: "2024-02-18",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord_01",
    orderNumber: "NEX-241-89012",
    clientId: "usr_client_01",
    clientName: "Marc Ndong Mba",
    clientPhone: "+241 077 45 89 12",
    storeIds: ["store_02"],
    items: [
      {
        id: "item_01",
        productId: "prod_01",
        productTitle: "Coffret Chocolat Artisanal Pur Kango",
        productPrice: 9900,
        productImage: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=300&auto=format&fit=crop&q=80",
        quantity: 2,
        storeId: "store_02",
        storeName: "Saveurs & Terroir du Gabon",
      },
      {
        id: "item_02",
        productId: "prod_05",
        productTitle: "Pot d'Odika Pur Torréfié de Makokou",
        productPrice: 8500,
        productImage: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=300&auto=format&fit=crop&q=80",
        quantity: 1,
        storeId: "store_02",
        storeName: "Saveurs & Terroir du Gabon",
      },
    ],
    subtotalAmount: 28300,
    deliveryFee: 2000,
    totalAmount: 30300,
    paymentMethod: "airtel_money",
    paymentStatus: "paid",
    status: "in_delivery",
    deliveryLocation: {
      province: "Estuaire",
      ville: "Libreville",
      quartier: "Nzeng-Ayong",
      repere_texte: "Face pharmacie de Nzeng-Ayong, grand portail vert à 50m du carrefour GP",
      telephone: "+241 077 45 89 12",
    },
    deliveryId: "del_01",
    estimatedDeliveryDate: "Aujourd'hui entre 15h30 et 16h30",
    createdAt: "2024-02-27T10:15:00Z",
    updatedAt: "2024-02-27T11:00:00Z",
  },
  {
    id: "ord_02",
    orderNumber: "NEX-241-89013",
    clientId: "usr_client_02",
    clientName: "Sandrine Boulingui",
    clientPhone: "+241 066 33 22 11",
    storeIds: ["store_01"],
    items: [
      {
        id: "item_03",
        productId: "prod_02",
        productTitle: "Sculpture Façonnée Main en Pierre de Mbigou",
        productPrice: 39000,
        productImage: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=300&auto=format&fit=crop&q=80",
        quantity: 1,
        storeId: "store_01",
        storeName: "L'Atelier Pierre de Mbigou & Arts",
      },
    ],
    subtotalAmount: 39000,
    deliveryFee: 2500,
    totalAmount: 41500,
    paymentMethod: "moov_money",
    paymentStatus: "paid",
    status: "confirmed",
    deliveryLocation: {
      province: "Estuaire",
      ville: "Akanda",
      quartier: "Angondjé Amissa",
      repere_texte: "Villa N°14, après le collège Amissa Bongo, barrière noire",
      telephone: "+241 066 33 22 11",
    },
    estimatedDeliveryDate: "Demain à 11h00",
    createdAt: "2024-02-27T11:45:00Z",
    updatedAt: "2024-02-27T11:50:00Z",
  },
];

export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: "del_01",
    orderId: "ord_01",
    orderNumber: "NEX-241-89012",
    livreurId: "usr_livreur_01",
    livreurName: "Yannick Obame",
    livreurPhone: "+241 066 98 74 12",
    status: "in_transit",
    pickupLocation: {
      province: "Estuaire",
      ville: "Akanda",
      quartier: "Angondjé Château",
      repere_texte: "Boutique Saveurs du Gabon, Carrefour Gigi",
      telephone: "+241 074 12 34 56",
    },
    dropoffLocation: {
      province: "Estuaire",
      ville: "Libreville",
      quartier: "Nzeng-Ayong",
      repere_texte: "Face pharmacie de Nzeng-Ayong, grand portail vert",
      telephone: "+241 077 45 89 12",
    },
    clientName: "Marc Ndong Mba",
    clientPhone: "+241 077 45 89 12",
    repereLivraison: "Face pharmacie de Nzeng-Ayong, grand portail vert à 50m du carrefour GP",
    deliveryFee: 2000,
    courierPayout: 1500,
    otpCode: "2410",
    notes: "Appeler le client 10 minutes avant l'arrivée au carrefour GP.",
    timeline: [
      {
        time: "10:15",
        title: "Commande validée",
        description: "Paiement Airtel Money confirmé avec succès",
        completed: true,
      },
      {
        time: "10:40",
        title: "Colis préparé par la boutique",
        description: "Boutique Saveurs du Gabon à Angondjé",
        completed: true,
      },
      {
        time: "11:15",
        title: "Pris en charge par le livreur",
        description: "Livreur Yannick Obame en route vers Nzeng-Ayong",
        completed: true,
      },
      {
        time: "15:30 (Estimé)",
        title: "Livraison en cours",
        description: "Remise en main propre contre code SMS",
        completed: false,
      },
    ],
    createdAt: "2024-02-27T10:15:00Z",
    assignedAt: "2024-02-27T11:00:00Z",
  },
];
